import { run } from "hardhat";
import * as fs from "fs";
import * as path from "path";

interface DeploymentData {
    network: string;
    chainId: number;
    timestamp: string;
    contracts: Record<string, string>;
}

/**
 * Load deployed addresses from env vars (DEPLOYED_*) or fall back to
 * reading from the deployment/<network>.json file generated by deploy scripts.
 */
function loadAddresses(): { name: string; address: string }[] {
    const addresses: { name: string; address: string }[] = [];

    const push = (name: string, envKey: string) => {
        const a = process.env[envKey]?.trim();
        if (a) addresses.push({ name, address: a });
    };

    // Try env vars first
    push("OracleAggregator", "DEPLOYED_ORACLE_AGGREGATOR");
    push("VaultCore", "DEPLOYED_VAULT_CORE");
    push("PositionToken", "DEPLOYED_POSITION_TOKEN");
    push("TradingCore", "DEPLOYED_TRADING_CORE");
    push("MarketCalendar", "DEPLOYED_MARKET_CALENDAR");
    push("DividendManager", "DEPLOYED_DIVIDEND_MANAGER");
    push("AllowListCompliance", "DEPLOYED_COMPLIANCE_MANAGER");
    push("DividendKeeper", "DEPLOYED_DIVIDEND_KEEPER");
    push("TradingCoreViews", "DEPLOYED_TRADING_CORE_VIEWS");
    push("MockUSDC", "DEPLOYED_MOCK_USDC");

    if (addresses.length > 0) return addresses;

    // Fall back to deployment JSON
    const network = process.env.HARDHAT_NETWORK;
    if (!network) {
        console.log("No DEPLOYED_* env vars and no --network flag. Nothing to verify.");
        return [];
    }

    const jsonPath = path.join(process.cwd(), "deployment", `${network}.json`);
    if (!fs.existsSync(jsonPath)) {
        console.log(`No deployment file at ${jsonPath} and no DEPLOYED_* env vars set.`);
        return [];
    }

    console.log(`Loading addresses from ${jsonPath}`);
    const data: DeploymentData = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));

    const contractMap: Record<string, string> = {
        oracleAggregator: "OracleAggregator",
        vaultCore: "VaultCore",
        positionToken: "PositionToken",
        tradingCore: "TradingCore",
        marketCalendar: "MarketCalendar",
        dividendManager: "DividendManager",
        complianceManager: "AllowListCompliance",
        dividendKeeper: "DividendKeeper",
        tradingCoreViews: "TradingCoreViews",
        mockUsdc: "MockUSDC",
    };

    for (const [key, contractName] of Object.entries(contractMap)) {
        const addr = data.contracts?.[key];
        if (addr) addresses.push({ name: contractName, address: addr });
    }

    return addresses;
}

async function main() {
    const addresses = loadAddresses();

    if (addresses.length === 0) {
        console.log("No addresses to verify. Set DEPLOYED_* env vars or deploy first.");
        process.exit(0);
    }

    console.log(`\nVerifying ${addresses.length} contract(s)...\n`);

    let verified = 0;
    let failed = 0;

    for (const { name, address } of addresses) {
        try {
            await run("verify:verify", { address });
            console.log(`✓ Verified: ${name} at ${address}`);
            verified++;
        } catch (e: unknown) {
            const msg = e instanceof Error ? e.message : String(e);
            if (msg.includes("Already Verified") || msg.includes("already verified")) {
                console.log(`✓ Already verified: ${name} at ${address}`);
                verified++;
            } else {
                console.error(`✗ Failed to verify ${name}:`, msg);
                failed++;
            }
        }
    }

    console.log(`\nVerification complete: ${verified} verified, ${failed} failed.`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
